platform:
  - amd64

environment:
  global:
    VSVER: 14
    my_secret:
      secure: UzwZuxCL9RvUOiAZsc+OqN4oAhqtXa5OO7IDm94gzAc=

  matrix:
    - PYTHON: "C:\\Python36-x64"

install:
  - .\ci\install.bat

build: off

test_script:
  - .\ci\run_appveyor.bat
