--- docker/python_connector_tests/Dockerfile-x86_64_base
+++ docker/python_connector_tests/Dockerfile-x86_64_base
@@ -1,4 +1,5 @@
-FROM quay.io/pypa/manylinux2010_x86_64
+ARG BASE_IMAGE
+FROM $BASE_IMAGE
 
 # This is to solve permission issue, read https://denibertovic.com/posts/handling-permissions-with-docker-volumes/
 RUN curl -o /usr/local/bin/gosu -SL "https://github.com/tianon/gosu/releases/download/1.11/gosu-amd64"
