name: Jira Issue Transition
description: Change status of specific Jira issue
branding:
  icon: 'chevron-right'
  color: 'blue'
inputs:
  issue:
    description: Key of the issue to be transitioned
    required: true
runs:
  using: 'node12'
  main: './dist/index.js'
