package:
    name: snowflake_connector_python
    version: "1.2.3"

source:
    path: /tmp/anaconda_workspace/src

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - boto3 ==1.3.1
        - botocore ==1.4.26
        - future
        - six
        - pytz
        - pycrypto ==2.6.1
        - pyopenssl ==0.15.1
        - cryptography ==1.2.3
        - cffi ==1.6.0

about:
    home: https://www.snowflake.net/
    license: Apache 2.0
    license_file: /tmp/anaconda_workspace/src/LICENSE.txt
    summary: Snowflake Connector for Python
