/**
 * @file sf_mini_core.h
 * @brief C API for sf_mini_core library
 *
 * This header file provides the C API for the sf_mini_core Rust library.
 * This file is auto-generated by cbindgen. Do not edit manually!
 */

#ifndef SF_MINI_CORE_H
#define SF_MINI_CORE_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually.
 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif  // __cplusplus

/**
 * Returns the full version string for sf_core.
 *
 * This function returns a pointer to a static null-terminated string
 * containing the version of sf_core.
 *
 * @return A pointer to a static string containing the version.
 *         The caller must NOT free this pointer.
 *         The returned string is valid for the lifetime of the program.
 *
 * @note Thread-safe: Yes
 * @note This function never returns NULL
 *
 * Example usage:
 * @code
 *   const char* version = sf_core_full_version();
 *   printf("Version: %s\n", version);
 * @endcode
 *
 * # Safety
 *
 * The returned pointer points to a static string that is valid for the lifetime
 * of the program. The caller must not free the returned pointer.
 */
const char *sf_core_full_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif /* SF_MINI_CORE_H */
