name: Test Installation

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

concurrency:
  # older builds for the same pull request number or branch should be cancelled
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  test-installation-boto:
    name: Test boto3 optional dependency
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: 3.12

      - name: Test default installation (should exclude boto)
        shell: bash
        run: |
          python -m venv test_default_env
          source test_default_env/bin/activate

          python -m pip install .

          # Check that boto3 and botocore are NOT installed by default
          pip freeze | grep boto && exit 1

          # Deactivate and clean up
          deactivate
          rm -rf test_default_env

      - name: Test installation with [boto3] (should include boto)
        shell: bash
        run: |
          python -m venv test_boto_env
          source test_boto_env/bin/activate

          python -m pip install '.[boto3]'
          pip freeze | grep boto || exit 1  # boto3/botocore should be installed

          # Deactivate and clean up
          deactivate
          rm -rf test_boto_env

  test-installation-aioboto:
    if: false  # temporarily disable aio - SNOW-2905263
    name: Test aioboto optional dependency
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: 3.12

      - name: Test installation with [aio] (should include aioboto)
        shell: bash
        run: |
          python -m venv test_no_boto_env
          source test_no_boto_env/bin/activate

          python -m pip install '.[aio]'

          # Check that aioboto3 and aiobotocore are installed
          pip freeze | grep aioboto || exit 1  # aioboto3 and aiobotocore should be installed

          # Deactivate and clean up
          deactivate
          rm -rf test_no_boto_env
